import { formatDate, type MarkerStatus } from '@aspire-bloods/shared';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Card } from '../../components/ui/Card';
import { Skeleton } from '../../components/ui/Skeleton';
import { EmptyState } from '../../components/ui/EmptyState';
import { ErrorState } from '../../components/ui/ErrorState';
import { LinkButton } from '../../components/ui/LinkButton';
import { Reveal } from '../../components/motion/Reveal';
import { staggerDelay } from '../../components/motion/stagger';
import { apiFetch } from '../../lib/api';
import { downloadFromApi } from '../../lib/download';
import { useToast } from '../../components/ui/Toast';
import { type MarkerRow } from '../../lib/patientPortal';
import {
  byAttentionThenName,
  byName,
  filterCountLabel,
  groupByHealthArea,
  matchesMarkerQuery,
  matchesStatusFilter,
  statusFilterCounts,
  type MarkerSort,
  type StatusFilter,
} from '../../lib/markerCopy';
import { Button } from '../../components/ui/Button';
import { AreaGroupHeading, CountsStrip } from './ResultsSummary';
import { MARKER_GRID_CLASS, MarkerResultCard } from './MarkerResultCard';
import type { ResultsArrangement, ResultsFilters, ViewReportsCategories } from './resultsView';

/**
 * Every marker ever tested, one card each — the "By marker" view.
 *
 * The first tab and the default, because the question it answers is the one
 * the report list structurally cannot: somebody wondering "how's my vitamin D
 * doing" has no reason to remember which panel it was on. Each card carries
 * the latest value, where that value sits on its range, and its status.
 *
 * It draws the SAME card as an opened report (see MarkerResultCard) — these are
 * the same object at two scopes, one report's markers against every marker ever
 * tested, and they were two visual languages for no reason anybody could name.
 * They are now the same shape as well: the sparkline that used to sit at the
 * foot of a card here (and nowhere on a report) is gone, replaced by the range
 * bar every measured result gets. Direction of travel is a question with a
 * whole page devoted to it, one click away.
 *
 * Above the grid: the same joined at-a-glance unit the report header carries,
 * counting across every marker on record, with this view's own PDF beside it.
 *
 * Sorting defaults to "needs attention first" rather than alphabetical — the
 * first question this list gets asked is almost never "what begins with A".
 * The four orders themselves are MARKER_SORTS, in lib/markerCopy, because the
 * picker that offers them now lives in the page's one control bar rather than
 * in a second bar down here.
 */

/** Change measured relative to the marker's own reference band, so markers on different scales sort against each other. */
function relativeMovement(m: MarkerRow): number {
  if (m.delta === null) return -1;
  const band = m.referenceHigh - m.referenceLow || Math.abs(m.value ?? 0) || 1;
  return Math.abs(m.delta) / band;
}

/** One comparator per sort, so grouping reorders nothing — it only breaks the grid into sections. */
function comparatorFor(sort: MarkerSort): (a: MarkerRow, b: MarkerRow) => number {
  if (sort === 'NAME') return byName;
  if (sort === 'RECENT')
    return (a, b) => (a.sampleDate < b.sampleDate ? 1 : a.sampleDate > b.sampleDate ? -1 : a.name.localeCompare(b.name));
  if (sort === 'MOVEMENT') return (a, b) => relativeMovement(b) - relativeMovement(a) || a.name.localeCompare(b.name);
  return byAttentionThenName;
}

/**
 * The panel, the date and the result count this value came from — as three
 * separate facts rather than one middot-joined line.
 *
 * "Signature · 3 February 2026 · 3 results" was a single string, and in a
 * 15rem column the browser broke it wherever it liked: about a third of the
 * time that was in the middle of the date. The card stacks them one per line
 * now, with the date always on its own, so it reads as a date rather than as
 * the middle of a sentence — see MarkerCardMeta.
 */
function markerMeta(marker: MarkerRow) {
  return {
    // Optional: a report needn't have a panel behind it, and the card omits
    // the line entirely rather than printing an empty one.
    panelName: marker.panelName,
    sampleDate: formatDate(marker.sampleDate),
    resultCount: marker.resultCount,
  };
}

/** Health areas as the catalogue sends them — `note` is the overlap caveat shown in a group heading. */
interface CategoryOption {
  key: string;
  name: string;
  note?: string | null;
}

/**
 * The By marker view's own download, beside its at-a-glance strip.
 *
 * A different document from a report's summary and generated by a different
 * function (generateAllMarkersPdf), because it answers a different question:
 * the latest value for every marker on record, across every report, rather
 * than one panel addressed as a letter and signed by whoever released it.
 * Same server-side pipeline, same three faces, same status vocabulary.
 *
 * Streamed rather than fetched as a signed link — "every marker I have"
 * changes the moment the next report is released, so there is nothing stored
 * for a link to point at. See the /patient/markers-pdf route.
 */
function DownloadMarkersButton() {
  const [downloading, setDownloading] = useState(false);
  const { show } = useToast();

  async function handleDownload() {
    setDownloading(true);
    try {
      await downloadFromApi('/api/patient/markers-pdf', 'aspire-markers.pdf');
    } catch {
      show('That download could not be prepared. Please try again.', 'error');
    } finally {
      setDownloading(false);
    }
  }

  return (
    <Button variant="secondary" loading={downloading} onClick={() => void handleDownload()}>
      Download markers (PDF)
    </Button>
  );
}

export function MarkerListView({
  filters,
  arrangement,
  onClearFilters,
  onCategoriesAvailable,
  onStatusCounts,
  onSelectStatus,
}: {
  filters: ResultsFilters;
  arrangement: ResultsArrangement;
  onClearFilters: () => void;
  onStatusCounts?: (counts: Record<StatusFilter, number>) => void;
  /** The at-a-glance segments double as the status filter, exactly as a report's do. */
  onSelectStatus?: (status: MarkerStatus | 'ALL') => void;
} & ViewReportsCategories) {
  const [markers, setMarkers] = useState<MarkerRow[] | null>(null);
  const [error, setError] = useState<unknown>(null);
  const [categories, setCategories] = useState<CategoryOption[]>([]);
  const { query, statusFilter, categoryFilter } = filters;
  const { grouping, markerSort: sort } = arrangement;

  const load = useCallback(() => {
    setError(null);
    setMarkers(null);
    // A failed markers load is not "nothing tested yet" — that empty state
    // tells a patient with released results they have none. Surface the
    // failure with a retry instead.
    apiFetch<MarkerRow[]>('/patient/markers')
      .then(setMarkers)
      .catch(setError);
    // Health areas for the category filter. A failure here costs the category
    // picker and nothing else, so it degrades rather than blocking the page.
    apiFetch<CategoryOption[]>('/content/marker-categories')
      .then(setCategories)
      .catch(() => setCategories([]));
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  /**
   * Genetic indicators, food sensitivities and microbiome proportions never
   * appear on this screen at all. It is a list of things with a value, a range
   * and a direction of travel, and none of those three has any of them.
   */
  const measured = useMemo(
    () => (markers ?? []).filter((m) => (m.resultType ?? 'MEASURED') === 'MEASURED'),
    [markers],
  );

  // Counts for the status-filter options, one pass rather than one filter per
  // option per render.
  const statusCounts = useMemo(() => statusFilterCounts(measured), [measured]);

  const compare = comparatorFor(sort);

  const visible = useMemo(() => {
    const filtered = measured.filter(
      (m) =>
        matchesStatusFilter(m.status, statusFilter) &&
        matchesMarkerQuery(m, query) &&
        (categoryFilter === 'ALL' || (m.categoryKeys ?? []).includes(categoryFilter)),
    );
    return [...filtered].sort(compare);
  }, [measured, query, statusFilter, categoryFilter, compare]);

  // Only areas this patient actually has results in — offering a filter that
  // can only ever return nothing is worse than not offering it.
  const filterableCategories = useMemo(() => {
    const present = new Set(measured.flatMap((m) => m.categoryKeys ?? []));
    return categories.filter((c) => present.has(c.key));
  }, [categories, measured]);

  // Grouped under health-area headings, same rendering as the report view.
  // A marker in four areas appears under all four; the count above stays the
  // distinct one, so grouping never inflates it.
  const grouped = useMemo(
    () => (grouping === 'HEALTH_AREA' ? groupByHealthArea(visible, filterableCategories, compare) : []),
    [grouping, visible, filterableCategories, compare],
  );

  // What each area holds before the filters, so a heading can say "3 of 21".
  const areaTotals = useMemo(() => {
    const all = groupByHealthArea(measured, filterableCategories);
    return new Map(all.map((g) => [g.key, g.markers.length]));
  }, [measured, filterableCategories]);

  const areaNotes = useMemo(() => new Map(categories.map((c) => [c.key, c.note])), [categories]);

  // The page's pickers offer exactly what this view can answer for.
  useEffect(() => {
    onCategoriesAvailable?.(filterableCategories.map((c) => ({ key: c.key, name: c.name })));
  }, [filterableCategories, onCategoriesAvailable]);
  useEffect(() => {
    onStatusCounts?.(statusCounts);
  }, [statusCounts, onStatusCounts]);

  const filtersApplied = query.trim() !== '' || statusFilter !== 'ALL' || categoryFilter !== 'ALL';
  const clearFilters = onClearFilters;

  /**
   * The one line a marker card carries that a report's cannot: whether these
   * values can be read as a series at all.
   *
   * The sparkline that used to sit here is gone, replaced by the range bar at
   * the top of every card (see MarkerResultCard). A sparkline answers "which
   * way is it going" at a size too small to answer it honestly, and it was
   * absent on a report — so the same card came out two different shapes on two
   * screens. The trend is one click away on the marker's own page, plotted
   * against real time and with room to be read.
   *
   * What survives is the caveat, because it is a fact about the data rather
   * than a picture of it: a series whose values needed a unit conversion
   * nobody holds is not a series, and saying so is the honest version of
   * refusing to draw the line.
   */
  function markerFooter(marker: MarkerRow) {
    if (marker.comparable) return null;
    return <span className="text-xs text-espresso/80">Not comparable with earlier results</span>;
  }

  return (
    <>
      {error ? (
        <ErrorState
          error={error}
          subject="your markers"
          onRetry={load}
          backTo={{ to: '/overview', label: 'Back to overview' }}
        />
      ) : markers === null ? (
        <div className={MARKER_GRID_CLASS} aria-busy="true" aria-label="Loading your markers">
          {[0, 1, 2, 3, 4, 5, 6, 7].map((i) => (
            <Card key={i} padding="tight">
              <Skeleton className="h-4 w-28" />
              <Skeleton className="mt-3 h-8 w-20" />
              <Skeleton className="mt-3 h-3 w-24" />
            </Card>
          ))}
        </div>
      ) : markers.length === 0 ? (
        <div className="max-w-2xl">
          <EmptyState
            title="Nothing tested yet"
            description="Every marker from your first released results is listed here."
            action={<LinkButton to="/overview">Back to overview</LinkButton>}
          />
        </div>
      ) : (
        <>
          {/* THE SAME JOINED UNIT the report header carries, counting across
              every marker on record rather than one panel's worth. The By
              marker view had no summary at all: it went straight from the
              control bar into forty cards, so the one question the list is
              opened with — "is anything worth a look" — could only be answered
              by reading all of them.

              It counts what is ON RECORD and not what is currently filtered,
              deliberately: it is the denominator the filters act on, and a
              summary that moved with them would be a count of the thing the
              reader can already see. The segments still double as the status
              filter, exactly as the report's do.

              Its own download sits beneath it, in the same relationship the
              report's downloads have to its summary. */}
          <CountsStrip
            markers={measured}
            title="All markers at a glance"
            activeStatus={statusFilter}
            onSelectStatus={onSelectStatus}
            action={<DownloadMarkersButton />}
            className="mb-14"
          />

          {/* The live count and the way out of an over-narrow filter. Every
              control that produced them — search, both filters, the grouping
              and the sort — is in the one bar above. */}
          <div className="flex flex-wrap items-baseline justify-between gap-x-6 gap-y-3">
            <p className="eyebrow">Every marker you’ve had tested</p>
            <div className="flex flex-wrap items-center gap-4">
              <p className="tabular text-sm text-espresso/80" role="status">
                {filterCountLabel(visible.length, measured.length)}
              </p>
              {filtersApplied && (
                <Button variant="secondary" onClick={clearFilters}>
                  Clear filters
                </Button>
              )}
            </div>
          </div>

          {visible.length === 0 ? (
            <div className="mt-6 max-w-2xl">
              <EmptyState
                title="Nothing matches those filters"
                action={filtersApplied ? <Button onClick={clearFilters}>Clear filters</Button> : undefined}
              />
            </div>
          ) : grouping === 'HEALTH_AREA' ? (
            <div className="mt-6 flex flex-col gap-12">
              {grouped.map((g) => (
                <section key={g.key} aria-labelledby={`markers-area-${g.key}`}>
                  <AreaGroupHeading
                    id={`markers-area-${g.key}`}
                    name={g.name}
                    note={areaNotes.get(g.key)}
                    markers={g.markers}
                    total={areaTotals.get(g.key) ?? g.markers.length}
                  />
                  <div className={MARKER_GRID_CLASS}>
                    {g.markers.map((marker, i) => (
                      <Reveal key={marker.markerId} delay={staggerDelay(i, 30)} className="h-full">
                        <MarkerResultCard
                          marker={marker}
                          meta={markerMeta(marker)}
                          footer={markerFooter(marker)}
                        />
                      </Reveal>
                    ))}
                  </div>
                </section>
              ))}
            </div>
          ) : (
            <div className={`mt-6 ${MARKER_GRID_CLASS}`}>
              {visible.map((marker, i) => (
                <Reveal key={marker.markerId} delay={staggerDelay(i, 30)} className="h-full">
                  <MarkerResultCard marker={marker} meta={markerMeta(marker)} footer={markerFooter(marker)} />
                </Reveal>
              ))}
            </div>
          )}
        </>
      )}
    </>
  );
}
