/**
 * The analyte-map audit.
 *
 *   npm run audit:analytes --workspace=apps/server
 *
 * ─── THE PROBLEM, STATED HONESTLY ─────────────────────────────────────────
 *
 * A Randox result row carries no marker id and no marker code. The only
 * identity it has is the `analyte` string, with `group` and `displayName`
 * beside it. `modules/randox/analyteMap.ts` is the whole bridge, and it does
 * exactly two passes — exact, then normalised — against the names and aliases
 * our own catalogue holds.
 *
 * Which means the coverage figure everybody quotes is a measurement of the
 * catalogue against itself. Every clinical marker resolves from its own
 * catalogue name. Zero have been checked against a real Randox payload. And 86
 * of them answer to exactly ONE spelling, so a single difference in how Randox
 * print any of those loses a result to the exception queue.
 *
 * (The 86 is unchanged by the QUALITATIVE reclassification, and it is worth
 * saying why: 65 of them are MEASURED and 21 are the UTI organisms, the body
 * composition analyser and the prostate cancer risk score, which moved result
 * type and did not stop arriving in a payload. `analyteMappingCoverage()`
 * counts both, deliberately — see the note on `measured` there.)
 *
 * ─── WHAT THIS REPORT IS FOR ──────────────────────────────────────────────
 *
 * Naming the 86, so the first real delivery can be checked against a list
 * rather than against a feeling. They are the markers with no alias and no
 * override: no second chance if the spelling differs.
 *
 * ─── WHAT IT DOES NOT DO ──────────────────────────────────────────────────
 *
 * It does not invent Randox spellings to pad the alias list. The exception
 * queue catches an ABSENT mapping; nothing catches a WRONG one. An invented
 * alias that happens to collide with another analyte files a real measurement
 * under the wrong marker on a real patient's record, unwatched — which is the
 * one failure this whole path is built to make impossible.
 *
 * The live version of these numbers, including what real deliveries have
 * confirmed, is on the ingestion log screen in the admin console. This report
 * is the static, checkable list.
 */
import 'dotenv/config';
import fs from 'node:fs';
import path from 'node:path';
import { resolveCatalogueMarkers } from '@aspire-bloods/shared';
import {
  ANALYTE_OVERRIDES,
  URINE_ANALYTE_KEYS,
  analyteMappingCoverage,
  normaliseAnalyte,
  resolveAnalyte,
} from '../src/modules/randox/analyteMap.js';
import { prisma } from '../src/db/client.js';

const OUT = path.resolve(process.cwd(), '../../docs/audits/analyte-mapping.md');

const esc = (s: unknown) => String(s ?? '').replace(/\|/g, '\\|');

async function main() {
  const coverage = analyteMappingCoverage();
  const catalogue = resolveCatalogueMarkers();
  // The same population analyteMappingCoverage() reports on: everything a
  // clinician acts on, plus everything that carries a finding.
  const clinical = catalogue.filter((m) => m.resultType === 'MEASURED' || m.resultType === 'QUALITATIVE');
  const byKey = new Map(catalogue.map((m) => [m.key, m]));

  // What real deliveries have actually confirmed. Zero rows is the expected
  // state before the first one, and is reported as such rather than as a gap
  // in the report.
  const observations = await prisma.randoxAnalyteObservation
    .findMany({ include: { marker: { select: { key: true, name: true } } }, orderBy: { lastSeenAt: 'desc' } })
    .catch(() => []);
  const resolvedObs = observations.filter((o) => o.status === 'RESOLVED');
  const unmappedObs = observations.filter((o) => o.status === 'UNMAPPED');
  const confirmedMarkerKeys = new Set(resolvedObs.map((o) => o.marker?.key).filter(Boolean));

  const lines: string[] = [];
  const p = (s = '') => lines.push(s);

  p('# Analyte map audit');
  p();
  p('Generated by `apps/server/scripts/auditAnalyteMap.ts`. Read-only.');
  p();

  p('## The number, and what kind of number it is');
  p();
  p('| | |');
  p('| --- | --- |');
  p(`| Clinical markers in the catalogue (MEASURED + QUALITATIVE) | **${coverage.measured}** |`);
  p(`| Resolve from their own catalogue name | **${coverage.resolvesFromOwnName}** |`);
  p(`| Carry at least one alternative spelling | **${coverage.withAlternativeSpelling}** |`);
  p(`| Answer to exactly ONE spelling | **${coverage.singleSpellingOnly.length}** |`);
  p(`| Reached through an explicit, sourced override of a Randox spelling | **${coverage.overrides}** |`);
  p(`| Confirmed against a real Randox payload, by the code alone | **${coverage.confirmedAgainstRealPayload}** |`);
  p(`| Confirmed against a real Randox payload, from deliveries | **${confirmedMarkerKeys.size}** |`);
  p();
  p(
    '**The last two rows are the point of this report.** The first of them is hardcoded to zero in `analyteMappingCoverage()` and stays hardcoded: it answers "what does the code claim on its own evidence", and the honest answer is nothing, because nothing in the map was derived from a Randox payload. It must never become a computed number, because every computation available to it would be counting assumptions.',
  );
  p();
  p(
    `The second is counted from \`RandoxAnalyteObservation\`, which records the analyte string of every result row that arrives and what became of it. That is evidence rather than assumption, so it may grow. It currently stands at **${confirmedMarkerKeys.size}**${
      confirmedMarkerKeys.size === 0
        ? ' — no delivery has been ingested in the database this ran against.'
        : '.'
    }`,
  );
  p();
  p(
    `Everything above the last two rows is the catalogue agreeing with itself. ${coverage.resolvesFromOwnName} of ${coverage.measured} markers resolving from their own names says that our name index is internally consistent. It says nothing whatsoever about how Randox spell them.`,
  );
  p();

  p('## The whole catalogue, not just the clinical part');
  p();
  p(
    'The map has to cover every marker Randox can send a result for, which is all of them — a food IgG item and a microbiome proportion arrive on the same payload as a potassium. The clinical figures above are MEASURED plus QUALITATIVE; this is everything.',
  );
  p();
  p('| Result type | Markers | Answer to one spelling only |');
  p('| --- | --- | --- |');
  for (const [type, v] of Object.entries(coverage.byResultType).sort((a, b) => b[1].total - a[1].total)) {
    p(`| ${type} | ${v.total} | ${v.singleSpelling} |`);
  }
  p();
  p(
    '**The SENSITIVITY row WAS the single largest risk here, and is now closed (Aug 2026).** Our catalogue holds every food item with a disambiguating suffix \u2014 `Cod (IgG)`, `Casein (IgG)` \u2014 because deduplicating by name across categories would otherwise merge `Egg White` into a protein assay. That suffix is OURS, not Randox\u2019s, and nobody has ever seen what Randox print. While all 207 answered to the suffixed spelling alone, Randox printing the food name bare meant not one of them resolved and the whole food-sensitivity section of a Signature report landed in the exception queue at once \u2014 which is not a queue, it is an outage with a list.',
  );
  p(
    '**Both spellings now resolve.** The bare form is an alias on every sensitivity marker, which is why the count above is 0 rather than 207. This is NOT a guess at a Randox spelling and does not weaken the rule that governs the rest of this file: there is still no fuzzy matching, no similarity scoring and no substring fallback anywhere in `analyteMap.ts`. It is our own name accepted with and without a suffix we added ourselves. `Celery`, `Mustard Seed` and `Egg White` are still exactly the names a future allergen panel would reuse \u2014 if one ever collides, the index records BOTH claims and the row is refused as AMBIGUOUS rather than filed against a guess, and `tests/analyteObservations.test.ts` fails first, before the collision can reach a delivery.',
  );
  p();

  p(`## The ${coverage.singleSpellingOnly.length} clinical markers that answer to exactly one spelling`);
  p();
  p(
    'No alias, no override. Each of these resolves on its catalogue name and on nothing else, so one difference in how Randox print it — a different word order, an abbreviation in or out of brackets, a hyphen — sends that result to the exception queue instead of onto a report.',
  );
  p();
  p(
    '**This is the check-first list.** When the first real delivery lands, these are the markers to compare against the analyte strings it carries, in this order, before anything else. Every other marker has a second spelling to fall back on.',
  );
  p();
  p('| Marker | Key | The one spelling it answers to | Health areas |');
  p('| --- | --- | --- | --- |');
  for (const m of coverage.singleSpellingOnly.sort((a, b) => a.name.localeCompare(b.name))) {
    const full = byKey.get(m.key);
    p(
      `| ${esc(m.name)} | \`${m.key}\` | \`${esc(normaliseAnalyte(m.name))}\` | ${esc(
        (full?.categoryKeys ?? []).join(', ') || '—',
      )} |`,
    );
  }
  p();

  p('## Markers with a second spelling to fall back on');
  p();
  p(
    `${coverage.withAlternativeSpelling} of them. These carry an alias, an override, or both — a Randox spelling that differs from our catalogue name still has somewhere to land. Listed after the ${coverage.singleSpellingOnly.length} above rather than before, because they are the lower risk.`,
  );
  p();
  p('| Marker | Spellings it answers to |');
  p('| --- | --- |');
  for (const m of clinical.filter((x) => !coverage.singleSpellingOnly.some((s) => s.key === x.key)).sort((a, b) => a.name.localeCompare(b.name))) {
    const overrides = Object.entries(ANALYTE_OVERRIDES).filter(([, k]) => k === m.key).map(([n]) => n);
    const urine = Object.entries(URINE_ANALYTE_KEYS).filter(([, k]) => k === m.key).map(([n]) => `${n} (urine only)`);
    p(`| ${esc(m.name)} | ${esc([...new Set([m.name, ...m.aliases, ...overrides, ...urine])].join(' · '))} |`);
  }
  p();

  p('## Names that identify more than one marker');
  p();
  if (coverage.ambiguous.length === 0) {
    p('None. Every catalogue name resolves to exactly one marker.');
  } else {
    p(
      'These are REFUSED at ingestion rather than guessed at, which is correct: a row whose name genuinely identifies two different tests does not say which one it is, and picking is how a urine dipstick glucose becomes a fasting plasma glucose.',
    );
    p();
    p('| Name | Could be |');
    p('| --- | --- |');
    for (const a of coverage.ambiguous) p(`| ${esc(a.name)} | ${esc(a.candidates.join(', '))} |`);
  }
  p();

  p('## The explicit overrides, and why the list is short');
  p();
  p(
    "Each of these is a Randox spelling our catalogue corrects. They come from the catalogue's own provenance note — the recorded list of Randox spelling slips — and from nowhere else. The list is short because the sample report PDF in `specs/` uses subset fonts with a custom encoding and its analyte column cannot be extracted mechanically, so not one entry here was derived from it. Inventing plausible spellings and calling them sourced would be worse than an empty list: the exception queue catches an absent mapping, and nothing catches a wrong one.",
  );
  p();
  p('| Randox print | We hold | Marker exists |');
  p('| --- | --- | --- |');
  for (const [randox, key] of Object.entries(ANALYTE_OVERRIDES)) {
    p(`| \`${esc(randox)}\` | \`${key}\` | ${byKey.has(key) ? 'yes' : '**NO — broken override**'} |`);
  }
  p();

  p('## What real deliveries have actually said');
  p();
  if (observations.length === 0) {
    p(
      'Nothing yet. `RandoxAnalyteObservation` is empty in the database this ran against, which means no Randox delivery has been ingested here. That is the expected state, and it is exactly why the confirmed figure above is zero rather than reassuring.',
    );
  } else {
    p(
      `**${observations.length}** distinct analyte spellings have arrived. **${resolvedObs.length}** resolved, **${unmappedObs.length}** did not. The live version of this, with the exception queue and the accept control, is on the ingestion log screen in the admin console.`,
    );
    p();
    p('| Analyte as Randox sent it | Sample type | Seen | Outcome | Filed against | How |');
    p('| --- | --- | --- | --- | --- | --- |');
    for (const o of observations) {
      p(
        `| \`${esc(o.analyte)}\` | ${esc(o.sampleType ?? '—')} | ${o.sightings} | ${o.status} | ${esc(
          o.marker?.name ?? '—',
        )} | ${esc(o.via ?? '—')} |`,
      );
    }
  }
  p();

  p('## For Randox');
  p();
  p(
    '- **The exact analyte strings each panel returns**, as printed in `reportResults.analyte`. One real GetOrderResultDetail payload per panel would confirm or correct the whole map in an afternoon, and would turn the confirmed figure above from a zero into a number.',
  );
  p(
    '- **The void and caveat code list.** Unrelated to the map, and the other thing that silently costs results — an unrecognised code withholds one by design. The boot guard still refuses to start with `RANDOX_TRANSPORT=live` while the code map is the checked-in placeholder, and that guard is not to be weakened.',
  );
  p();

  // A broken override — a spelling pointed at a marker key that no longer
  // exists — is silent at runtime until the day Randox send that spelling. It
  // is worth failing this script over rather than printing a table row.
  const broken = Object.entries(ANALYTE_OVERRIDES).filter(([, key]) => !byKey.has(key));
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, lines.join('\n'));
  console.log(`Wrote ${OUT}`);
  console.log(
    `${coverage.measured} measured markers, ${coverage.resolvesFromOwnName} resolve from their own name, ` +
      `${coverage.singleSpellingOnly.length} on one spelling only, ${coverage.overrides} overrides, ` +
      `${confirmedMarkerKeys.size} confirmed by a real payload (${observations.length} spellings seen).`,
  );
  await prisma.$disconnect();
  if (broken.length > 0) {
    throw new Error(`${broken.length} override(s) point at a marker key the catalogue no longer has: ${broken.map(([n, k]) => `${n} → ${k}`).join(', ')}`);
  }
  // Sanity: the coverage figure must still be derived, not stale.
  void resolveAnalyte;
}

main().catch(async (e) => {
  console.error(e);
  await prisma.$disconnect();
  process.exit(1);
});
